import { useState, createContext, useContext, type ReactNode } from 'react';
import { AlertCircle, CheckCircle2, ChevronDown, Loader2, Search, X } from 'lucide-react';

export function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-2.5" data-testid="brand-securelife"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[hsl(var(--accent))] text-[hsl(var(--foreground))] shadow-sm"><span className="font-display text-lg font-extrabold">S</span></span>{!compact && <span className="font-display text-[17px] font-extrabold tracking-[-.03em]">secure<span className="text-[hsl(var(--primary))]">life</span></span>}</div>;
}

export function Button({ children, variant = 'primary', className = '', loading = false, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'outline' | 'quiet' | 'danger'; loading?: boolean }) {
  const testId = (props as { 'data-testid'?: string })['data-testid'];
  const styles = { primary: 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] hover:brightness-110', outline: 'border border-[hsl(var(--border))] bg-[hsl(var(--card))] text-[hsl(var(--foreground))] hover:border-[hsl(var(--primary))] hover:text-[hsl(var(--primary))]', quiet: 'text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))] hover:text-[hsl(var(--foreground))]', danger: 'bg-[hsl(var(--destructive))] text-white hover:brightness-110' };
  return <button data-testid={testId} {...props} disabled={props.disabled || loading} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-4 text-sm font-semibold transition-all duration-200 disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`}>{loading && <Loader2 size={16} className="animate-spin" />}{children}</button>;
}

export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'danger' | 'accent' }) {
  const styles = { neutral: 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]', success: 'bg-[#dbeee5] text-[#176247]', warning: 'bg-[#fff0d1] text-[#8b5b10]', danger: 'bg-[#fbe1de] text-[#a42f2a]', accent: 'bg-[#fff0d1] text-[#8b5b10]' };
  return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold uppercase tracking-[.06em] ${styles[tone]}`} data-testid="status-badge">{children}</span>;
}
export function statusTone(status?: string): 'neutral' | 'success' | 'warning' | 'danger' { const s = status?.toUpperCase() || ''; return s.includes('APPROV') || s === 'ACTIVE' ? 'success' : s.includes('PENDING') || s.includes('REVIEW') || s.includes('SUBMIT') ? 'warning' : s.includes('REJECT') || s.includes('CANCEL') || s.includes('EXPIRE') ? 'danger' : 'neutral'; }
export function StatusBadge({ status }: { status?: string }) { return <Badge tone={statusTone(status)}>{(status || 'Unknown').replaceAll('_', ' ')}</Badge>; }

export function Field({ label, error, hint, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string; hint?: string }) {
  const testId = (props as { 'data-testid'?: string })['data-testid'];
  return <label className="block space-y-1.5"><span className="text-sm font-semibold text-[hsl(var(--foreground))]">{label}</span><input data-testid={testId} {...props} className={`w-full rounded-lg border bg-[hsl(var(--card))] px-3.5 py-2.5 text-sm outline-none transition focus:border-[hsl(var(--primary))] focus:ring-2 focus:ring-[hsl(var(--primary))]/15 ${error ? 'border-[hsl(var(--destructive))]' : 'border-[hsl(var(--input))]'}`} />{hint && !error && <span className="block text-xs text-[hsl(var(--muted-foreground))]">{hint}</span>}{error && <span className="block text-xs text-[hsl(var(--destructive))]">{error}</span>}</label>;
}
export function TextArea({ label, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string }) { const testId = (props as { 'data-testid'?: string })['data-testid']; return <label className="block space-y-1.5"><span className="text-sm font-semibold">{label}</span><textarea data-testid={testId} {...props} className="min-h-28 w-full resize-y rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--card))] px-3.5 py-2.5 text-sm outline-none focus:border-[hsl(var(--primary))] focus:ring-2 focus:ring-[hsl(var(--primary))]/15" /></label>; }
export function SelectField({ label, options, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label: string; options: string[] }) { const testId = (props as { 'data-testid'?: string })['data-testid']; return <label className="block space-y-1.5"><span className="text-sm font-semibold">{label}</span><span className="relative block"><select data-testid={testId} {...props} className="w-full appearance-none rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--card))] px-3.5 py-2.5 pr-9 text-sm outline-none focus:border-[hsl(var(--primary))]">{options.map((option) => <option value={option} key={option}>{option.replaceAll('_', ' ')}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-3 top-3 text-[hsl(var(--muted-foreground))]" /></span></label>; }

export function LoadingState({ label = 'Loading your secure view' }: { label?: string }) { return <div className="space-y-3" aria-label={label} data-testid="loading-state"><div className="h-24 animate-pulse rounded-xl bg-[hsl(var(--muted))]" /><div className="grid gap-3 sm:grid-cols-3"><div className="h-28 animate-pulse rounded-xl bg-[hsl(var(--muted))]" /><div className="h-28 animate-pulse rounded-xl bg-[hsl(var(--muted))]" /><div className="h-28 animate-pulse rounded-xl bg-[hsl(var(--muted))]" /></div></div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="flex flex-col items-center justify-center rounded-xl border border-[#f2d3cf] bg-[#fff8f6] px-6 py-12 text-center" data-testid="error-state"><AlertCircle className="mb-3 text-[hsl(var(--destructive))]" /><h3 className="font-display font-bold">We hit a snag</h3><p className="mt-1 max-w-md text-sm text-[hsl(var(--muted-foreground))]">{message}</p>{retry && <Button variant="outline" className="mt-4" onClick={retry} data-testid="button-retry">Try again</Button>}</div>; }
export function EmptyState({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="rounded-xl border border-dashed border-[hsl(var(--border))] bg-[hsl(var(--card))] px-6 py-14 text-center" data-testid="empty-state"><div className="mx-auto mb-3 grid h-11 w-11 place-items-center rounded-full bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]"><CheckCircle2 size={21} /></div><h3 className="font-display font-bold">{title}</h3><p className="mx-auto mt-1 max-w-md text-sm text-[hsl(var(--muted-foreground))]">{detail}</p>{action && <div className="mt-5">{action}</div>}</div>; }

type Toast = { id: number; text: string; type: 'success' | 'error' };
const ToastContext = createContext<{ toast: (text: string, type?: Toast['type']) => void } | null>(null);
export function ToastProvider({ children }: { children: ReactNode }) { const [items, setItems] = useState<Toast[]>([]); const toast = (text: string, type: Toast['type'] = 'success') => { const id = Date.now(); setItems((i) => [...i, { id, text, type }]); window.setTimeout(() => setItems((i) => i.filter((x) => x.id !== id)), 4500); }; return <ToastContext.Provider value={{ toast }}>{children}<div className="fixed bottom-5 right-5 z-[60] grid w-[min(360px,calc(100vw-2rem))] gap-2">{items.map((item) => <div key={item.id} className={`flex items-start gap-3 rounded-xl border bg-[hsl(var(--card))] p-4 shadow-[var(--shadow-soft)] ${item.type === 'error' ? 'border-[#f2d3cf]' : 'border-[#c9e6da]'}`} role="status" data-testid="toast"><CheckCircle2 size={18} className={item.type === 'error' ? 'text-[hsl(var(--destructive))]' : 'text-[hsl(var(--primary))]'} /><span className="flex-1 text-sm font-medium">{item.text}</span><button onClick={() => setItems((i) => i.filter((x) => x.id !== item.id))} aria-label="Dismiss notification" data-testid="button-dismiss-toast"><X size={15} /></button></div>)}</div></ToastContext.Provider>; }
export function useToast() { const value = useContext(ToastContext); if (!value) throw new Error('useToast must be used inside ToastProvider'); return value; }
export function SearchBox({ value, onChange, placeholder = 'Search' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="relative"><Search size={16} className="absolute left-3 top-3 text-[hsl(var(--muted-foreground))]" /><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-10 w-full rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--card))] pl-9 pr-3 text-sm outline-none focus:border-[hsl(var(--primary))]" data-testid="input-search" /></div>; }